name: Go
on: [push]
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - run: echo "event starting"
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v halo.go

    - name: Test
      run: go test -v halo_test.go halo.go

    - name: Get version
      run: |
        cat version
        ver=`cat version`      
        ver=`expr $ver + 1`
        echo $ver > version

    - name: Tag
      run: |
        git config --global user.name "trinexe"
        git config --global user.email "katrincheung@google.com"

        git add .
        git commit -m "update version"
        git push
        git tag git_v0.0.$ver;
        git push origin git_v0.0.$ver;
