name: Go
on: [push]
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - run: echo "event starting"
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v halo.go

    - name: Test
      run: go test -v halo_test.go halo.go

    - name: Get version
      id: get_version
      run: |
        cat version
        ver=`cat version`
        ver=`expr $ver + 1`
        echo $ver > version

        git config --global user.name "trinexe"
        git config --global user.email "katrincheung@google.com"

        git add .
        git commit -m "update version"
        git push

        git tag git_v0.0.$ver
        git push origin git_v0.0.$ver

        echo ::set-output name=TAG::git_v0.0.$ver

    - name: Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.TAG }}
        release_name: Release ${{ steps.get_version.outputs.TAG }}
        draft: false
        prerelease: false
        
    - name: Update asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: halo
        asset_name: halo_binary
        asset_content_type: application/zip
