name: Go
on: [push]
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - run: echo "event starting"
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v halo.go

    - name: Test
      run: go test -v halo_test.go halo.go

    - name: Tag
      run: |
        git tag git_v0.0.1;
        git push origin git_v0.0.1;
